from sqlalchemy import Column, Integer, DECIMAL, Text, BOOLEAN

from core.domain.base_model import BaseModel


class Drug(BaseModel):
    __tablename__ = 'drugs'

    drugbank_drug_id = Column(Integer, nullable=False)
    drug_name = Column(Text, nullable=False)
    drugbank_id = Column(Text, nullable=False)
    smiles = Column(Text, nullable=False)
    drug_type = Column(Text, nullable=False)
    description = Column(Text, nullable=False)
    average_mass = Column(Integer, nullable=False)
    monoisotopic_mass = Column(Integer, nullable=False)
    state = Column(Text, nullable=False)
    indication = Column(Text, nullable=False)
    pharmacodynamics = Column(Text, nullable=False)
    mechanism_of_action = Column(Text, nullable=False)
    toxicity = Column(Text, nullable=False)
    metabolism = Column(Text, nullable=False)
    absorption = Column(Text, nullable=False)
    half_life = Column(Text, nullable=False)
    protein_binding = Column(Text, nullable=False)
    route_of_elimination = Column(Text, nullable=False)
    volume_of_distribution = Column(Text, nullable=False)
    clearance = Column(Text, nullable=False)
    classification_description = Column(Text, nullable=False)
    total_text = Column(Text, nullable=False)
    classification_direct_parent = Column(Text, nullable=False)
    classification_kingdom = Column(Text, nullable=False)
    classification_superclass = Column(Text, nullable=False)
    classification_class_category = Column(Text, nullable=False)
    classification_subclass = Column(Text, nullable=False)
    bioavailability = Column(Integer, nullable=False)
    ghose_filter = Column(Integer, nullable=False)
    h_bond_acceptor_count = Column(Integer, nullable=False)
    h_bond_donor_count = Column(Integer, nullable=False)
    log_p = Column(DECIMAL(10, 8), nullable=False)
    log_s = Column(DECIMAL(10, 8), nullable=False)
    mddr_like_rule = Column(Integer, nullable=False)
    molecular_formula = Column(Text, nullable=False)
    molecular_weight = Column(DECIMAL(10, 8), nullable=False)
    monoisotopic_weight = Column(DECIMAL(10, 8), nullable=False)
    number_of_rings = Column(Integer, nullable=False)
    physiological_charge = Column(Integer, nullable=False)
    pka_strongest_acidic = Column(DECIMAL(10, 8), nullable=False)
    pka_strongest_basic = Column(DECIMAL(10, 8), nullable=False)
    polar_surface_area = Column(DECIMAL(10, 8), nullable=False)
    polarizability = Column(DECIMAL(10, 8), nullable=False)
    refractivity = Column(DECIMAL(10, 8), nullable=False)
    rotatable_bond_count = Column(Integer, nullable=False)
    rule_of_five = Column(Integer, nullable=False)
    water_solubility = Column(Text, nullable=False)
    rdkit_3d = Column(Text, nullable=False)
    rdkit_2d = Column(Text, nullable=False)
    has_enzyme = Column(BOOLEAN, nullable=False)
    has_pathway = Column(BOOLEAN, nullable=False)
    has_target = Column(BOOLEAN, nullable=False)
    has_smiles = Column(BOOLEAN, nullable=False)
